### ISSUE TITLE
All Workspaces Numbers Are Displayed

### ISSUE THREAD

**Issue by Nesousx** [andyrichardson/simply-workspaces#5] opened 2021-08-10 13:22 UTC
Hi Andy,

Thanks for this great extension !

I am also, a recent convert from i3wm, like [Nikita from the feature request](https://github.com/andyrichardson/simply-workspaces/issues/2) (which I also "+1ed").

I have an issue where all the workspaces numbers are displayed from 1 to 10, even though I do not have programs open on several of those.

My config looks like so :

```
dconf read /org/gnome/shell/overrides/dynamic-workspaces
false
```
```
dconf read /org/gnome/desktop/wm/preferences/num-workspaces
10
```
I have no idea where to look for / debug this issue. Let me know if I can provide any other log / config.

Thanks in advance,
Denis

**Comment by HighIQHobo** [comment] 2021-08-16 00:52
I am also having a problem similar to this.  I have found that all workspace numbers only display when there is an application open on my secondary monitor.  This also only happens when workspaces are set to only appear on the primary display.  Whenever I enable "Workpaces span displays" in gnome-tweaks, everything works as intended.

**Demo:**

https://user-images.githubusercontent.com/21997383/129498093-3a9389a3-9820-455b-9598-15c300f355d7.mp4

**Comment by Nesousx** [comment] 2021-08-16 07:55
Hi,

Thanks for the info. 

I am only using one screen currently, and have already "Workspaces span display" ON, but still the issue I described. Changing this option doesn't help either.

**Comment by andyrichardson** [comment] 2021-08-18 10:12
Thanks for the feedback folks - the gif is massively helpful :+1: 

I've tried to summarise the problem in #1 but the main issue is that when "Workspaces on primary display only" is enabled, any windows on the secondary monitor are considered to be a member of all workspaces.

I've [pushed a workaround](https://github.com/andyrichardson/simply-workspaces/commit/23cc6bd9df340bac1c9f51a7059aca442de38a68) that has (mostly) been working on my end. Would be great if you folks could try it out and let me know if that solves your problem!

**Comment by Nesousx** [comment] 2021-08-18 16:24
Hi Andy,

Thanks for the patch. However, it doesn't fix anything for me. :(

**Comment by andyrichardson** [comment] 2021-08-19 16:24
Are you sure you're using the patch from the latest master (not the gnome extensions store)? 

It's working on my end

![Screenshot from 2021-08-19 17-23-17](https://user-images.githubusercontent.com/10779424/130106188-0c571fcb-6f93-40df-b9e2-71d8defbe3b3.png)

**Comment by Nesousx** [comment] 2021-08-19 16:28
I downloaded the extension.js via curl to `.local/share/gnome-shell/extensions/simply.workspaces@andyrichardson.dev` :+1: 

```
ls -lhtr
total 56K
-rw-r--r-- 1 nesousx nesousx 1,4K juin  10 21:00 ui.js
-rw-r--r-- 1 nesousx nesousx  186 juin  10 21:00 stylesheet.css
-rw-r--r-- 1 nesousx nesousx  35K juin  10 21:00 LICENSE
-rw------- 1 nesousx nesousx  321 juin  22 14:36 metadata.json
-rw-r--r-- 1 nesousx nesousx 2,7K juin  22 16:13 extension.bkp
-rw-rw-r-- 1 nesousx nesousx 3,1K août  18 12:16 extension.js
```
Then I restarted gnome-shell and even relogged my session. I might have done something wrong though...

Cheerds,
Denis

**Comment by HighIQHobo** [comment] 2021-08-19 20:08
Just installed the latest patch and everything seems to be fixed on my end!  Thanks for the patch!

**Closed** 2022-08-04 11:33 UTC
Labels: bug
